man_manuia_homepage:
    pattern:  /
    defaults: { _controller: "ManManuiaBundle:Default:index" }

man_manuia_test:
    pattern:  /test
    defaults: { _controller: "ManManuiaBundle:Default:test" }
