man_manuia_homepage:
    pattern:  /
    defaults: { _controller: "ManManuiaBundle:Default:index" }

man_manuia_hello:
    pattern:  /hello/{name}
    defaults: { _controller: "ManManuiaBundle:Default:hello" }
