parameters:
#    man_manuia.example.class: Man\Bundle\ManuiaBundle\Example

services:
    twig.extension.timeago:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\TimeAgoExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    twig.extension.gravatar:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\GravatarExtension
        tags:
            - { name: twig.extension }

    twig.extension.camelize:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\CamelizeExtension
        tags:
            - { name: twig.extension }

    twig.extension.decamelize:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\DecamelizeExtension
        tags:
            - { name: twig.extension }

    twig.extension.normalizestring:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\NormalizeStringExtension
        tags:
            - { name: twig.extension }

    twig.extension.flickr_desc:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\FlickrDescriptionExtension
        tags:
            - { name: twig.extension }
