parameters:
#    man_manuia.example.class: Man\Bundle\ManuiaBundle\Example

services:
    twig.extension.timeago:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\TimeAgoExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

    twig.extension.gravatar:
        class: Man\Bundle\ManuiaBundle\Twig\Extension\GravatarExtension
        tags:
            - { name: twig.extension }
