<?php

namespace Man\Bundle\BlogBundle\Entity;


/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostFactory
{
    /**
     * 
     * @param type $title
     * @param type $slug
     * @param type $content
     * @return \Man\Bundle\BlogBundle\Entity\Post
     */
    public function createPost($title, $slug, $content = null, $description = null)
    {
        $post = new Post();
        $post->setTitle($title);
        $post->setSlug($slug);
        $post->setContent($content);
        $post->setDescription($description);
        
        return $post;
    }
}
