man_photography:
    resource: "@ManPhotographyBundle/Resources/config/routing.yml"
    prefix:   /photography

man_admin:
    resource: "@ManAdminBundle/Controller/"
    type:     annotation

man_blog:
    resource: "@ManBlogBundle/Controller/"
    type:     annotation

admin_logout:
    pattern:   /admin/logout

man_manuia:
    resource: "@ManManuiaBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
linkedin_login:
    pattern: /login/check-linkedin

flickr_login:
    pattern: /login/check-flickr
